# Generated by Django 4.2.11 on 2024-03-14 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('thread_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('topic', models.IntegerField(choices=[(0, 'News'), (1, 'Strategies'), (2, 'Analysis'), (3, 'Economic'), (4, 'Crypto'), (5, 'Finance'), (6, 'Education')], default=0)),
                ('thread_text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
