# Generated by Django 4.2.11 on 2024-03-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_on']},
        ),
    ]
