# Generated by Django 4.2.11 on 2024-03-19 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_alter_comment_options_alter_thread_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='follow',
            field=models.ManyToManyField(blank=True, default=None, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
